version: '3.7'

networks:
  net:
    # driver: overlay
  only_fbeat:
    external: true

services:
  simple_golang_app:
    image: simple_golang_app
    container_name: simple_golang_app
    build:
      context: app/golang/
      dockerfile: Dockerfile
      args:
        TEST_ENV: $TEST_ENV
    networks:
      - net
    labels:
        co.elastic.logs/enabled: "true" # for Filebeat


  test_golang_app_2:
    image: test_golang_app_2
    container_name: test_golang_app_2
    build:
      context: app/golang/
      dockerfile: Dockerfile
    networks:
      - net
    # labels:
    #     co.elastic.logs/enabled: "true" # for Filebeat
